#!/bin/bash

function usage
{
    echo "Usage: deb-install-deps <package>"
    echo ""
    echo "Search the required dependencies for the given package and"
    echo "install them with it."
    echo ""
    echo "Those dependencies that are system libraries will be installed"
    echo "for armhf or arm64, depending of the package architecture."
    echo ""
}


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--h" ];
then
    usage
    abort
fi




PACKAGE=$1
PACKAGE_FILENAME=$(basename $1)
PACKAGE_NAME=$(echo $PACKAGE_FILENAME | cut -d '_' -f 1)
DEB_DOWNLOADS="$HOME/.local/deb-downloads"
DEB_INSTALLS="$HOME/.local/installs"


echo "$PACKAGE_FILENAME" | grep i386 > /dev/null

if [ "$?" == "0" ];
then
    PACKAGE_ARCH="armhf"
else
    echo "$PACKAGE_FILENAME" | grep amd64 > /dev/null

    if [ "$?" == "0" ];
    then
        PACKAGE_ARCH="arm64"
    else
        echo "$PACKAGE_FILENAME" | grep aarch64 > /dev/null

        if [ "$?" == "0" ];
        then
            PACKAGE_ARCH="arm64"
        else
            PACKAGE_ARCH="armhf"
        fi
    fi
fi


if ! [ -d "$DEB_DOWNLOADS" ];
then
    mkdir -p "$DEB_DOWNLOADS"
fi

cd "$DEB_DOWNLOADS"

echo "Checking dependencies of ${PACKAGE} ..."

for dep in $(deb-deps ${PACKAGE_NAME});
do
    if [[ $dep == *lib* ]];
    then
        echo ""
        echo "Installing ${dep}:${PACKAGE_ARCH} ..."
        echo "======================================="
        apt install ${dep}:${PACKAGE_ARCH}

    else
        echo "Downloading ${dep} ..."
        echo "================================"
        apt download $dep

        if ! [ "$?" == "0" ];
        then
            abort "No package with that name was found."
        fi

        DEB_PACKAGE=$(ls ${dep}_*.deb)

        if [ -f "$DEB_PACKAGE" ];
        then
            deb-manual-install "$DEB_PACKAGE"
            cp -r "$DEB_INSTALLS/${dep}/*" "$DEB_INSTALLS/${PACKAGE}/"
            rm -r "$DEB_INSTALLS/${dep}"
        fi
    fi
done

