#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


ARCH=$(uname -m)

if ! [[ ARCH == armv* ]] || ! [ "$ARCH" == "arm64" ];
then
    abort "Box86 is intended for running x86 binaries in ARM platforms."
fi


if [ -f "/usr/local/bin/box86" ];
then
    abort "Box86 is already installed."
fi




DISTRO_NAME="debian"

if ! [ "$ANDROID_DATA" == "" ];
then
    BOX86="box86-android"
else
    BOX86="box86-generic-arm"
fi


echo "Installing Box86..."
echo "==================="

if ! [ -d "/usr/share/keyrings" ];
then
    make -p "/usr/share/keyrings"
fi

if ! [ -f "/usr/share/keyrings/box86-archive-keyring.gpg" ];
then
    wget -qO- "https://pi-apps-coders.github.io/box86-debs/KEY.gpg" | \
    gpg --dearmor -o "/usr/share/keyrings/box86-archive-keyring.gpg"

    if ! [ "$?" == "0" ];
    then
        abort "Could not intall Box86 GPG key."
    fi

    echo "Added GPG key to keyrings."
fi


if ! [ -f "/etc/apt/sources/list.d/box86.sources" ];
then
    echo "Types: deb" > /var/tmp/box86.sources

    echo "URIs: https://Pi-Apps-Coders.github.io/box86-debs/${DISTRO_NAME}" \
    >> /var/tmp/box86.sources

    echo "Suites: ./" >> /var/tmp/box86.sources
    echo "Signed-By: /usr/share/keyrings/box86-archive-keyring.gpg" \
    >> /var/tmp/box86.sources

    mv /var/tmp/box86.sources /etc/apt/sources.list.d/

    echo "Added sources list for APT."
fi


dpkg --add-architecture armhf
echo "Enabled armhf architecture in dpkg."

echo "Updating APT sources..."
echo "======================="
echo ""

apt update

echo ""
echo "Installing libc6 and ${BOX86} ..."
echo "================================="
echo ""

apt install -y libc6:armhf ${BOX86}

if ! [ "$?" == "0" ];
then
    echo ""
    abort "Failed installing."
fi

echo ""
echo "Finished!"

